version: '3.7'

services:
  moonbeam-bot:
    container_name: moonbeam-bot
    build: .
    image: jonheese/moonbeam-bot:latest
    environment:
      - BOT_ID=${BOT_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - MASTER_ID=${MASTER_ID}
      - MASTER_CHANNEL_ID=${MASTER_CHANNEL_ID}
      - MOONBEAM_IMAGE_URLS=${MOONBEAM_IMAGE_URLS}
      - QUOTES_FILE=${QUOTES_FILE}
      - TRIGGERS_FILE=${TRIGGERS_FILE}
      - PLEASANTRIES_FILE=${PLEASANTRIES_FILE}
      - WORDS_FILE=${WORDS_FILE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTOSCOOGLE_USERS=${AUTOSCOOGLE_USERS}
      - AUTOSCOOGLE_TRIGGERS=${AUTOSCOOGLE_TRIGGERS}
      - WT360_API_KEY=${WT360_API_KEY}
    network_mode: "bridge"
    restart: always
