version: '3.7'

services:
  moonbeam-bot:
    container_name: moonbeam-bot
    build: .
    image: jonheese/moonbeam-bot:latest
    environment:
      - Moonbeam_PLUGINS=${Moonbeam_PLUGINS}
      - Moonbeam_BOT_ID=${Moonbeam_BOT_ID}
      - Moonbeam_BOT_TOKEN=${Moonbeam_BOT_TOKEN}
      - CommandPlugin_MASTER_ID=${CommandPlugin_MASTER_ID}
      - CommandPlugin_MASTER_CHANNEL_ID=${CommandPlugin_MASTER_CHANNEL_ID}
      - MoonbeamPlugin_MASTER_ID=${MoonbeamPlugin_MASTER_ID}
      - MoonbeamPlugin_MASTER_CHANNEL_ID=${MoonbeamPlugin_MASTER_CHANNEL_ID}
      - MoonbeamPlugin_MOONBEAM_IMAGE_URLS=${MoonbeamPlugin_MOONBEAM_IMAGE_URLS}
      - MoonbeamPlugin_WORDS_FILE=${MoonbeamPlugin_WORDS_FILE}
      - QuotablePlugin_QUOTES_FILE=${QuotablePlugin_QUOTES_FILE}
      - TriggerPlugin_TRIGGERS_FILE=${TriggerPlugin_TRIGGERS_FILE}
      - DicePlugin_PLEASANTRIES_FILE=${DicePlugin_PLEASANTRIES_FILE}
      - DBStorePlugin_DB_HOST=${DBStorePlugin_DB_HOST}
      - DBStorePlugin_DB_NAME=${DBStorePlugin_DB_NAME}
      - DBStorePlugin_DB_USER=${DBStorePlugin_DB_USER}
      - DBStorePlugin_DB_PASSWORD=${DBStorePlugin_DB_PASSWORD}
      - AutoScooglePlugin_AUTOSCOOGLE_USERS=${AutoScooglePlugin_AUTOSCOOGLE_USERS}
      - AutoScooglePlugin_AUTOSCOOGLE_TRIGGERS=${AutoScooglePlugin_AUTOSCOOGLE_TRIGGERS}
      - WeatherPlugin_WT360_API_KEY=${WeatherPlugin_WT360_API_KEY}
      - ImpatientPlugin_RESPONSES=${ImpatientPlugin_RESPONSES}
      - ImpatientPlugin_MAX_THRESHOLD_SECS=${ImpatientPlugin_MAX_THRESHOLD_SECS}
      - ImpatientPlugin_RESPONSE_THRESHOLD_SECS=${ImpatientPlugin_RESPONSE_THRESHOLD_SECS}
      - ImpatientPlugin_COOLDOWN_SECS=${ImpatientPlugin_COOLDOWN_SECS}
    network_mode: "bridge"
    restart: always
